using AoDaiNhaUyen.Application.DTOs;

namespace AoDaiNhaUyen.Application.DTOs.Admin;

public sealed record LlmAuditLogListItemDto(
  Guid Id,
  string RequestId,
  string CorrelationId,
  string? TraceId,
  Guid? ActorUserId,
  string? ActorRole,
  string Source,
  string Provider,
  string? Model,
  string Operation,
  string? ToolName,
  string? RiskLevel,
  bool RequiresConfirmation,
  string Status,
  string? ErrorCode,
  long? LatencyMs,
  int? TotalTokens,
  decimal? EstimatedCost,
  DateTime CreatedAt,
  string? PromptPreviewRedacted,
  string? CompletionPreviewRedacted);

public sealed record LlmAuditLogDetailDto(
  Guid Id,
  string RequestId,
  string CorrelationId,
  string? TraceId,
  Guid? ConversationId,
  Guid? ThreadId,
  Guid? MessageId,
  Guid? AdminActionId,
  Guid? UserGeneratedImageId,
  Guid? ActorUserId,
  string? ActorRole,
  string Source,
  string? IpHash,
  string? UserAgentHash,
  string Provider,
  string? Model,
  string Operation,
  string? ActionType,
  string? ToolName,
  string? RiskLevel,
  bool RequiresConfirmation,
  Guid? ApprovedByUserId,
  DateTime? ApprovedAt,
  DateTime StartedAt,
  DateTime? CompletedAt,
  long? LatencyMs,
  int? PromptTokens,
  int? CompletionTokens,
  int? TotalTokens,
  decimal? EstimatedCost,
  string Status,
  string? ErrorCode,
  string? PromptPreviewRedacted,
  string? CompletionPreviewRedacted,
  string? InputMetadataJson,
  string? OutputMetadataJson,
  string? SafetyFlagsJson,
  string RedactionVersion,
  DateTime RetainUntil,
  DateTime CreatedAt);

public sealed record LlmAuditLogSearchRequest(
  int Page = 1,
  int PageSize = 20,
  DateTime? From = null,
  DateTime? To = null,
  string? Source = null,
  string? Status = null,
  string? Provider = null,
  string? Model = null,
  string? Operation = null,
  string? RiskLevel = null,
  string? ToolName = null,
  Guid? ActorUserId = null,
  Guid? ThreadId = null,
  Guid? ConversationId = null,
  string? RequestId = null,
  string? Q = null,
  string SortBy = "createdAt",
  string SortDir = "desc");

public sealed record LlmAuditLogStatsDto(
  int Total,
  int Success,
  int Failed,
  int Timeout,
  double AverageLatencyMs,
  int TotalTokens,
  decimal EstimatedCost);

public sealed record LlmAuditLogCreateDto(
  string Source,
  string Provider,
  string Operation,
  string? Model = null,
  string? Prompt = null,
  string? Completion = null,
  Guid? ActorUserId = null,
  string? ActorRole = null,
  Guid? ThreadId = null,
  Guid? ConversationId = null,
  Guid? MessageId = null,
  Guid? AdminActionId = null,
  Guid? UserGeneratedImageId = null,
  string? ToolName = null,
  string? RiskLevel = null,
  bool RequiresConfirmation = false,
  string? InputMetadataJson = null);

public sealed record LlmAuditLogUpdateDto(
  string Status,
  string? Completion = null,
  string? ErrorCode = null,
  int? PromptTokens = null,
  int? CompletionTokens = null,
  decimal? EstimatedCost = null,
  string? OutputMetadataJson = null,
  string? SafetyFlagsJson = null);
